#!/usr/bin/env bash
shopt -s dotglob
rm -rf .

if [ -z "$1" ]; then
  echo no version selected
  exit 1
fi

wget -O /tmp/kirby.zip https://codeload.github.com/getkirby/plainkit/zip/$1 \
  && unzip /tmp/kirby.zip -d /tmp/kirby \
  && rm /tmp/kirby.zip \
  && mv /tmp/kirby/plainkit-$1/* ./ \
  && rm -rf /tmp/kirby
